accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path("login/",  auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),  # Django 5 expects POST
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.home, name="home"),
]

phishing_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from tracking import views as tracking_views

urlpatterns = [
    path('', include(('tracking.urls','tracking'),namespace='tracking')),
    path('learn/<slug:slug>/', tracking_views.landing_view, name='learn'),
    path("admin/", admin.site.urls),
    path("", include("dashboard.urls")),
    path("auth/", include("accounts.urls")),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en-GB">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Phishing Portal{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="{% static 'css/colors.css' %}" rel="stylesheet">
</head>
<body>
  <div class="navbar">
    <div><strong>Phishing Portal</strong></div>
    <div>
      {% if request.user.is_authenticated %}
        <span>Hi, {{ request.user.first_name|default:request.user.username }}</span>
        <a href="{% url 'dashboard:home' %}" style="margin-left:12px;">Dashboard</a>
        <form action="{% url 'accounts:logout' %}" method="post" style="display:inline;">
    {% csrf_token %}
    <button class="btn-light" style="background:transparent;border:none;padding:0;color:#fff;cursor:pointer;">Logout</button>
  </form>
      {% else %}
        <a href="{% url 'accounts:login' %}">Login</a>
      {% endif %}
    </div>
  </div>

  <main class="container">
    {% block content %}{% endblock %}
  </main>
</body>
</html>